Divide swap into individual sell_base, sell_quote, and sell_base_to_base
woonetwork/WOOFi_Solana pull request #33
Opened 2024-10-02 21:38 UTC by toprince

PR for audit issue 73

https://github.com/sherlock-audit/2024-08-woofi-solana-deployment-judging/issues/73

Divide swap into individual sell_base, sell_quote, and sell_base_to_base

2024-10-06 02:30 UTC, fb-alexcq commented on programs/woofi/src/instructions/swap.rs
> +pub fn sell_quote(ctx: Context<Swap>, from_amount: u128, min_to_amount: u128) -> Result<()> {
better to be private, to align with Solidity wooPP ?

2024-10-06 03:08 UTC, fb-alexcq commented on programs/woofi/src/instructions/swap.rs
> +
Better also add another require:

   woopool_from.token_mint != woopool_to.token_mint

2024-10-06 03:09 UTC, fb-alexcq commented on tests/1_woofi_swap.ts
> +
Why not add some `assertEquals` for reserve checks?

2024-10-06 03:09 UTC, fb-alexcq requested changes
some inline comments.

2024-10-08 19:24 UTC, toprince commented on programs/woofi/src/instructions/swap.rs
> +
will add

2024-10-08 19:27 UTC, toprince commented on tests/1_woofi_swap.ts
> +
Ln 611:         assert.equal(fromPoolDataAfter.reserve.toNumber(), (fromPoolDataBefore.reserve.add(new BN(fromAmount)).sub(new BN(swapFee))).toNumber())

checked.

2024-10-08 19:38 UTC, toprince commented on programs/woofi/src/instructions/swap.rs
> +pub fn sell_quote(ctx: Context<Swap>, from_amount: u128, min_to_amount: u128) -> Result<()> {
make 3 fn to private now.

2024-10-09 11:26 UTC, fb-alexcq approved these changes

2024-10-09 14:10 UTC, merged